- DEV_NOTES.md
- PyPop/DataTypes.py
- PyPop/Utils.py
- README.md
- Singularity
- data/samples/minimal.ini
- data/singularity-test/USAFEL-UchiTelle-small-out.txt
- setup.py
I have a preliminary port from ```Numeric``` to ```numpy``` (#2).   This should make it a lot easier to build, package for PyPI and maintain going forward.  I've also updated the Singularity build script accordingly.  @akkornel & @vsoch, please do give it whirl and see if it builds for you.
@sjmack: please do also try this branch and see if all your files still work.  You'll need to use MacPorts to add the ```py27-numpy``` dependency (this is described in the README.md):
sudo port install py27-numpy
Then switch to this branch and rebuild:
git checkout numpy-port
./setup.py clean --all
./setup.py build
I've run everything through our current test suite and it all seems to be work, but with a major dependency change, would be good to have as many runs as possible.
> Port PyPop to Numpy

- Singularity
This PR has a number of changes to the Singularity bootstrap file:
• Ubuntu 17.04 is now being used as the base.
• SWIG 3.0.12 is being downloaded and built into the container, before PyPop builds.
• Some additional dependencies (packages) are being installed (for SWIG).
• Once building is complete, header files are removed from the container.
• py.test is now used for the tests.
With these changes, the container is now able to build using Singularity Hub!
> Singularity container bootstrap updates

- README.rst
drop `--user` from default instructions, because `pip install pypopgen`  generally "does the right thing" when installing on  a system-wide installation of Python.
> clarify instructions around use of `--user` in `pip install`

- website/README.md
Changed directory for `sphinx-build` from `docs` -> `website`
> Fix directory for sphinx files

- src/PyPop/xslt/emhaplofreq.xsl
converts all frequencies in scientific notation to decimal before rounding
> round all haplotype frequencies to 5 decimal places

- .github/workflows/documentation.yaml
piccolo-theme is now compatible with sphinx > 7.2 (https://github.com/piccolo-orm/piccolo_theme/issues/61), pinning most recent version
> piccolo-theme fixed: pin sphinx version to 7.2.5

- src/PyPop/Arlequin.py
- src/PyPop/Haplo.py
- src/PyPop/Utils.py
@rsingle I noticed that the calls to `math.sqrt` were producing `numpy` warnings.  I think this is due to being passed an `ndarray` rather than a scalar, so I modified this to take the first element of the `F_2_1_prime` or `F_1_2_prime`, but I'm not sure if this is generalizable solution.  Not sure why those variables are arrays in the first place.
> fix numpy + regex warnings

- DEV_NOTES.md
- NEWS.rst
- setup.py
- src/PyPop/Main.py
Also disables the `[Emhaplofreq]` deprecation for the time being (being deferred until `[Haplostats]` is fully documented/tested).
> End-user warning that undocumented module `[Haplostats]` is not yet supported

- .github/workflows/build_wheels.yml
- .zenodo.json
- CITATION.cff
- README.rst
* adds infrastructure for:
* bumping versions in `CITATION.cff` and `.zenodo.json` from release tag in GitHub release UI
* getting provisional DOI from Zenodo sandbox
* updating the DOI in `CITATION.cff`
* uploading to the Zenodo sandbox
* retagging the version to include the changes that were uploaded
* makes sure all builds and releases, and PyPI releases are now:
* downstream of the above so they include all the committed changes
* enable skipping of the retagging on non-Zenodo release
> Zenodo upload infrastructure

- pyproject.toml
They require special enabling in `pyproject.toml`.  Thanks to @odoublewen for the report.
> Enable MacOS Apple Silicon builds

- .github/workflows/build_wheels.yml
- pyproject.toml
needed to explicitly install the arm64 version of `gsl` via `brew` when building arm so that binary dependencies are packaged.
> Fix arm64 cross-compilation on MacOS

- CONTRIBUTING.rst
- setup.py
- tests/test_100k_Emhaplofreq.py
can restore at a later date if needed, currently cluttering up `install_requires` since it doesn't always have wheels for certain platforms like Windows
> remove `psutil` - only used by a currently skipped unit test

- .github/workflows/build_wheels.yml
Reverts alexlancaster/pypop#169
new `@v4` for both `download/upload-artifact` break the workflows
> Revert "Bump actions/download-artifact from 3 to 4"

- .github/workflows/build_wheels.yml
change syntax so that artifact names are unique according to: https://github.com/pypa/cibuildwheel/pull/1705
> update to `v4` of `download-artifact` / `upload-artifact`

- .github/workflows/build_wheels.yml
- pyproject.toml
* simplify workflow: use inheritance to make sure global environment variables are consistently set
* drop cross-compilation for all MacOS arm64 builds
* re-enable unit tests for MacOS arm64
> Enable native MacOS Apple Silicon runners

- .github/workflows/build_wheels.yml
- pyproject.toml
With the latest release of `gsl` of 2.8 on brew for MacOS, support for binary releases of `gsl` for versions of MacOS < 12 was dropped. This means that all CI builds currently fail on all MacOS systems.
In order to continue to support a minimum of 10.15 (Catalina) and later on x86, or 11.0 (Big Sur) and later on arm64, we would need to build `gsl` during the cibuildwheel process.  This would create a lot of maintenance overhead, and since Apple was EOLed Monterey and earlier, this PR creates wheels that will only install on MacOS 12 (Monterey) and later versions.
@sjmack : are you OK with making our minimum MacOS version be MacOS 12.0 (aka "Monterey")?
> Pin `gsl` bottles to 2.7.1 on macOS to preserve 10.15/Catalina on x86 and 11.0/Big Sur compatibility

- pyproject.toml
https://github.com/numpy/numpy/issues/24728
> enable PyPy 3.10 as numpy wheels now exist

- .github/workflows/build_wheels.yml
- pyproject.toml
- tests/test_gthwe.py
Some changes in the default runner packages, notably `swig` version bump from 4.2.1 to 4.3.0 caused builds to fail.
> update x86 runner to `macos-13`, pin `swig` version

- .github/workflows/build_wheels.yml
Drop QEMU emulation, use `ubuntu-22.04-arm` runners.
> Build Linux (`aarch64`) using new ARM64 runners

- .github/workflows/build_wheels.yml
- pyproject.toml
* adds `cp313-musllinux-aarch64` to default builds.
* moving `swig` to `build-system.requires` as per suggestion on https://github.com/pypa/cibuildwheel/issues/2302#issuecomment-2701728802
> Simplify `swig` installation via PyPI package, other build cleanups

- .github/workflows/build_wheels.yml
- tests/test_USAFEL.py
`windows-2019` image is now deprecated, see: https://github.com/actions/runner-images/issues/12045
> Update Windows image for CI: `windows-2019` -> `windows-2022`

- DEV_NOTES.md
- pyproject.toml
GitHub updated `brew` from 4.6.3 to 4.6.6, which disables installing bottles from tarballs, by default (https://github.com/Homebrew/brew/pull/20414), breaking the build. This re-enables installation by setting `HOMEBREW_DEVELOPER=1`
> Update MacOS `cibuildwheel` config to handle `brew` changes
